### ISSUE TITLE
Is it possible to add support for icons in the `actionButton`?

### ISSUE THREAD

**Issue by ShawnWx2019** [rstudio/bsicons#12]
I tried using `bs_icon` within `actionButton`, but encountered the following error:

```r
## code 
actionButton('action1.1', '1. Input file summary', icon = bs_icon("folder"))
## Error:
Error in validateIcon(icon) : 
  Invalid icon. Use Shiny's 'icon()' function to generate a valid icon
```

However, I can display `bs_icon` correctly in other places, such as:

```r
## shinyFiles::shinyDirButton
shinyDirButton(id = "MS2_table", 
               label = "Select MS2 folder",
               title = "The MS2 file folder:",
               buttonType = "default",
               class = NULL,
               icon = bs_icon("folder"),
               multiple = FALSE)
##> tabPanel
tabsetPanel(
  tabPanel(
    title = 'MS file check',
    height = '500px',
    width = "100%",
    icon = bs_icon('check2'),
    tags$h3("Summary of input file", style = 'color: #008080'),
    hr_main.....
```

Currently, it's not entirely clear what the reason for this discrepancy might be.

**Comment by Gotfrid** [comment]
I second this, but this change has to be made on the Shiny side - in `shiny:::validateIcon`.

In the meantime, it is possible to use `bs_icon` as label argument in `shiny::actionButton`:

```r
shiny::actionButton(
  inputid = "x",
  label = bsicons::bs_icon("arrow-counterclockwise"),
  icon = NULL
)
```

**Comment by gadenbuie** [comment]
Two more tips:

1. If you only use an icon in the button, be sure to include a `title` in the icon so that ARIA labels are properly set up for screen readers.

    ```r
    shiny::actionButton(
      inputid = "x",
      label = bsicons::bs_icon("arrow-counterclockwise", title = "Reload"),
      icon = NULL
    )
    ```

2. If you want to include text with the icon, use `label = tagList()`.

    ```r
    shiny::actionButton(
      inputid = "x",
      label = shiny::tagList(
        bsicons::bs_icon("arrow-counterclockwise"),
        "Reload"
      ),
      icon = NULL
    )
    ```

**Comment by ShawnWx2019** [comment]
> I second this, but this change has to be made on the Shiny side - in `shiny:::validateIcon`.
> 
> In the meantime, it is possible to use `bs_icon` as label argument in `shiny::actionButton`:
> 
> ```r
> shiny::actionButton(
>   inputid = "x",
>   label = bsicons::bs_icon("arrow-counterclockwise"),
>   icon = NULL
> )
> ```



> Two more tips:
> 
> 1. If you only use an icon in the button, be sure to include a `title` in the icon so that ARIA labels are properly set up for screen readers.
>    ```r
>    shiny::actionButton(
>      inputid = "x",
>      label = bsicons::bs_icon("arrow-counterclockwise", title = "Reload"),
>      icon = NULL
>    )
>    ```
> 2. If you want to include text with the icon, use `label = tagList()`.
>    ```r
>    shiny::actionButton(
>      inputid = "x",
>      label = shiny::tagList(
>        bsicons::bs_icon("arrow-counterclockwise"),
>        "Reload"
>      ),
>      icon = NULL
>    )
>    ```

Thank you both for your responses; they were very helpful to me. I'm looking forward to the `Shiny` updates and support for `bs_icon`!
