### ISSUE TITLE
No effect of changing class of bs_icon

### ISSUE THREAD

**Issue by udurraniAtPresage** [rstudio/bsicons#13]
Thank you for creating this package. Please note that the icon colour does not change if I change the class. I have `bsicons` version 0.1.1:

```
bslib::value_box(
    title = "Number of Participants",
    value = 5,
    class = "bg-primary text-white",
    showcase = bsicons::bs_icon(name = "person", class = "text-white")
)
```
![image](https://github.com/rstudio/bsicons/assets/142413619/0c6bf998-6d35-49d6-86d6-773912489ae7)

**Comment by gadenbuie** [comment]
Instead of `class = "bg-primary text-white"`, use `theme = "primary"`. In that case you also don't need to add the `text-white` class to the showcase icon.

```r
bslib::value_box(
    title = "Number of Participants",
    value = 5,
    theme = "primary",
    # class = "bg-primary text-white",
    showcase = bsicons::bs_icon(name = "person")
)
```

<img width="487" alt="image" src="https://github.com/rstudio/bsicons/assets/5420529/91f50053-7bad-4a0f-9b9c-e5b8415a7484">

**Comment by udurraniAtPresage** [comment]
Thanks! I believe the examples need to be updated. For instance, I see this example in the `bs_icon` docs:
```
up <- bs_icon("arrow-up-circle", size = "9em", class = "text-success")
up_fill <- bs_icon("arrow-up-circle-fill", size = "9em", class = "text-success")
```

**Comment by gadenbuie** [comment]
Oh, those examples should still work. The "not working" part was an interaction with `bslib::value_box()` where we add a special class to the value box when you don't set `theme`. That class was masking the effect of `class` on `bs_icon()`. If you set `value_box(theme = "primary")` (or any other theme), then `bs_icon(class = "text-success")` works again.

**Comment by udurraniAtPresage** [comment]
Ok, cool. Thank you.
